version: '3.8'
services:
  dev:
    image: postgres:13
    ports:
      - 2063:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user_service_fix
    networks:
      - new
  test:
    image: postgres:13
    ports:
      - 2064:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user_service_fix
    networks:
      - new
networks:
  new:
